configure_terminal: false

homebrew_installed_packages:
- git
- starship
- python@3.11
- helm
- kustomize
- podman
- openshift-cli

homebrew_cask_apps:
- firefox
- google-chrome
- bitwarden
- vlc
- steam
- iterm2
- visual-studio-code
- spotify

pip_packages:
- name: pipenv
- name: poetry
- name: black

configure_dock: true
dockitems_remove:
- Launchpad
- TV
- Music
- Podcasts
- News
- Photos
- Freeform

dockitems_persist:
- name: "iTerm"
  path: "/Applications/iTerm.app/"
  position: 2
- name: "Firefox"
  path: "/Applications/Firefox.app/"
  position: 4
- name: "Google Chrome"
  path: "/Applications/Google Chrome.app/"
  position: 5
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app/"
  position: 6
- name: "Steam"
  path: "/Applications/Steam/"
  position: 7
- name: "Spotify"
  path: "/Applications/Spotify.app/"
  position: 8
- name: "Adobe Lightroom Classic"
  path: "/Applications/Adobe Lightroom Classic.app/"
  position: 9

configure_dotfiles: true
dotfiles_repo: https://github.com/strangiato/dotfiles.git
dotfiles_repo_version: strangiato
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/code/dotfiles
dotfiles_files:
  # - .zshrc
  - .gitignore
  # - .inputrc
  - .osx
  - .vimrc

configure_osx: true
