---
- name: Get the path to preferred python default
  ansible.builtin.command: "which python{{ default_python_version }}"
  register: default_python_path

- name: Create python link
  ansible.builtin.file: 
    src: "/usr/local/bin/python3.11"
    dest: "/usr/local/bin/python"
    state: link
    force: true

- name: Create python3 link
  ansible.builtin.file: 
    src: "/usr/local/bin/python3.11"
    dest: "/usr/local/bin/python3"
    state: link
    force: true

- name: Get the path to preferred pip default
  ansible.builtin.command: "which pip{{ default_python_version }}"
  register: default_pip_path

- name: Create python link
  ansible.builtin.file:
    src: "/usr/local/bin/pip3.11"
    dest: "/usr/local/bin/pip"
    state: link
    force: true
