---
- name: install code extension
  shell: "code --install-extension {{ item }}"
  become: no
  register: result
  when:
    - vscode_extension is defined
  loop: "{{ vscode_extension }}"
  changed_when: result.stdout is not search('is already installed.')
